apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: kubernetes-cluster-vic5
  namespace: argo-managed-02-ns
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: builtin-generic-v3.5.0
      namespace: vmware-system-vks-public
    version: v1.34.2---vmware.2-vkr.2
    variables:
      - name: vsphereOptions
        value:
          persistentVolumes:
            defaultStorageClass: vks-standard-storage
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: vks-standard-storage
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-7efa4c656250806b3
    workers:
      machineDeployments:
        - class: node-pool
          name: kubernetes-cluster-vic5-np-y134
          replicas: 3
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-7efa4c656250806b3
          variables:
            overrides:
              - name: vmClass
                value: best-effort-xsmall

